sudo: false
language: node_js
node_js:
  - stable
  - 10
  - 8
  - 6
  - 4
script: 
  - npm test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'